import Head from 'next/head'
import Image from 'next/image'
import Feature from '../components/Feature'
import PizzaLis from '../components/PizzaList'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
    
      <Head>
        <title>PizzaBuddy in Dhaka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Feature/>
      <PizzaLis/>
    </div>
  )
}
